### ISSUE TITLE
discord wants my phone number

### ISSUE THREAD

**Issue by ninjafootball07** [ArchaicQuest/ArchaicQuest-II#9]
Hi @NinjaFootball07 here from discord. The channel is forcing me to add my phone number to talk. I don't feel comfortable giving my phone number to discord. Can you manually add me.

**Comment by LiamKenneth** [comment]
does this link work for you? https://discord.gg/nuf7FVq

**Comment by ninjafootball07** [comment]
![image](https://user-images.githubusercontent.com/17677587/60855493-2602f980-a1c1-11e9-8f0a-55db263499dd.png)
That link seems like a invite link? I already joined successfully, just the discord permissions seem to be set to require phone verified accounts. My discord is 2FA, but that didn't do it, as you see in the pic, discord wants my phone number on this channel. I don't really give that out. I tried google voice number even, still not good enough. NOTE: all the other discords I am in do not have this requirement. I assume it is a setting.

**Comment by MatthewJHBerry** [comment]
Works for me np.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Liam Kenneth <notifications@github.com> Date: 7/8/19  7:36 PM  (GMT-05:00) To: ArchaicQuest/ArchaicQuest-II <ArchaicQuest-II@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [ArchaicQuest/ArchaicQuest-II] discord wants my phone number (#9) does this link work for you? https://discord.gg/nuf7FVq

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ArchaicQuest/ArchaicQuest-II/issues/9?email_source=notifications\u0026email_token=AJP7QMRUFRX2GP7K43AO7S3P6PFRLA5CNFSM4H46CPQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZOUYRY#issuecomment-509430855",
"url": "https://github.com/ArchaicQuest/ArchaicQuest-II/issues/9?email_source=notifications\u0026email_token=AJP7QMRUFRX2GP7K43AO7S3P6PFRLA5CNFSM4H46CPQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZOUYRY#issuecomment-509430855",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LiamKenneth** [comment]
Ah, @ninjafootball07 I had a huge problem with spam bots spamming the channels with crappy pr0n links so tightened up on security.

 This and some other options have seemed to have helped but I have now changed the setting to "members need to be registered on discord for at least 5 minutes" so should work now for you.

 If I get more spam though I'll turn the verification back on
